version: '3'
services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=payments
    container_name: postgres_payments1
    ports:
      - "5432:5432"
